version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/TruSet/TruSetAPIServer
    steps:
      - checkout
      - restore_cache:
          keys:
          - go-api-vendor-{{ checksum "vendor/vendor.json" }}
          - go-api-vendor-
      - run: go get -u github.com/kardianos/govendor
      - run: govendor install +vendor,^program
      - save_cache:
          key: go-api-vendor-{{ checksum "vendor/vendor.json" }}
          paths:
            - vendor
  test:
    docker:
      - image: circleci/golang:1.9
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
    working_directory: /go/src/github.com/TruSet/TruSetAPIServer
    steps:
      - checkout
      - restore_cache:
          keys:
          - go-api-vendor-{{ checksum "vendor/vendor.json" }}
          - go-api-vendor-
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: go get -t -d -v ./...
      - run: go test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
