version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/TruSet/TruSetAPIServer
    steps:
      - checkout
      - restore_cache:
          keys:
          - go-api-vendor-{{ checksum "vendor/vendor.json" }}
          - go-api-vendor-
      - run: go get -u github.com/kardianos/govendor
      - run: govendor install +vendor,^program
      - save_cache:
          key: go-api-vendor-{{ checksum "vendor/vendor.json" }}
          paths:
            - vendor
  test:
    docker:
      - image: circleci/golang:1.9
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
    working_directory: /go/src/github.com/TruSet/TruSetAPIServer
    steps:
      - checkout
      - restore_cache:
          keys:
          - go-api-vendor-{{ checksum "vendor/vendor.json" }}
          - go-api-vendor-
      - run: go get -t -d -v ./...
      - run: go test -v -race ./...
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
