{
  postgresUri: "postgresql://postgres:postgres@postgres/postgres?sslmode=disable",
  ethereumRpc: "http://ethereum-node:8565",
  ethereumIpc: "/tmp/geth.ipc",
  ethereumWs: "http://ethereum-node:8566",
  commitRevealVotingContractAddress: "0x98ddc5698eb92c752b85af297016c13bd5151f61"
}
