{
  postgresUri: "postgresql://postgres:postgres@localhost/postgres?sslmode=disable",
  ethereumRpc: "https://rinkeby.infura.io/DPMnSwvrMeMKAo39FbFp",
  ethereumWs: "wss://rinkeby.infura.io/ws",
  commitRevealVotingContractAddress: "0xd57e5e62b3832cd512ecf8c2638eabdb4e42194e"
}
