basePath: /revealer/v0.1
definitions:
  database.CommitmentBody:
    properties:
      commitHash:
        example: 0x12345678909876543210123456789012
        type: string
      pollID:
        example: 0x12345678901234567890123456789012
        type: string
      salt:
        example: 5866984321541876564
        type: integer
      voteOption:
        example: 1
        type: integer
      voterAddress:
        example: 0x11223344556677889900
        type: string
    type: object
  database.Response:
    properties:
      message:
        example: vote will be revealed when voting closes
        type: string
    type: object
info:
  contact:
    email: greg.taschuk@consensys.net
    name: API Support
    url: https://www.truset.com/contact/
  description: A REST interface for submitting votes (e.g. Accept or Reject) on proposed
    data records.
  license:
    name: License TBD
    url: TBD
  termsOfService: ToS TBD
  title: TruSet Revealer API
  version: "0.1"
paths:
  /commitments/:
    post:
      description: Save a vote and the matching hash commitment to that vote
      operationId: store-commitment
      parameters:
      - description: The (about to be) committed vote details data you would like
          to store
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/database.CommitmentBody'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/database.Response'
        "406":
          description: Bad payload
          schema:
            $ref: '#/definitions/database.Response'
      summary: Store a commitment privately, to ensure it can be revealed at a later
        date
swagger: "2.0"
